FROM python:3.10-slim-buster

WORKDIR /app

COPY . /app

ENV FLASK_APP=app.py
# 1: dev 환경
ENV FLASK_DEBUG=1

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip uninstall tensorflow_io -y
RUN pip install tensorflow_io==0.24.0

RUN python3.10 -m pip install numpy

EXPOSE 5000

CMD ["flask", "run"]