FROM python:3.10-alpine

WORKDIR /app

COPY . /app

ENV FLASK_APP=app.py
# 1: dev 환경
ENV FLASK_DEBUG=1

RUN python -m pip install --upgrade pip

RUN pip install Flask==2.1.0
RUN pip install tensorflow==2.11.0

EXPOSE 5000

CMD ["flask", "run"]