FROM python:3.8-alpine

WORKDIR /app

COPY . /app

ENV FLASK_APP=app.py
# 0: prod 환경
ENV FLASK_DEBUG=0

RUN python -m pip install --upgrade pip

RUN pip install Flask==2.1.0
RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["flask", "run"]