FROM python:3.8-slim-buster

WORKDIR /app

COPY . /app

ENV FLASK_APP=app.py
# 1: dev 환경
ENV FLASK_DEBUG=1

RUN pip install --upgrade pip

RUN apt-get update && apt-get install -y libglib2.0-0 && \
    pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 5000

CMD ["flask", "run"]